# https://taskfile.dev

version: '3'

env:
  ENV: testing

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

includes:
  lab6:
    taskfile: ./taskfiles/lab6/Taskfile.yaml
    dir: ./taskfiles/lab6